### ISSUE TITLE
导出的html不全，不知道什么原因

### ISSUE THREAD

**Issue by Alvin0U0** [gyakkun/qq-mht2html#3]
用老版的QQMhtToHtml.exe，可以导出近100m的html文件，这个就只有6m多一点，粗看了下，所有的群聊记录都没导出来，请问可能是什么原因呢，不知道是不是设置问题？

**Comment by gyakkun** [comment]
可以发一下你的日志吗 位置在

`%HOMEPATH%\.qq-mht2html\log`

敏感信息请自行处理一下

**Comment by Alvin0U0** [comment]
> 可以发一下你的日志吗 位置在
> 
> `%HOMEPATH%\.qq-mht2html\log`
> 
> 敏感信息请自行处理一下

你好，我截取了一部分处理了下，基本上都是这种错误，如果有需要我可以再多放一些

2023-10-09 12:23:03,593 [DefaultDispatcher-worker-3] ERROR Mht2Html - Please raise a GitHub issue and attach the log file where you think the exception you hit is important.
2023-10-09 12:23:03,593 [DefaultDispatcher-worker-3] ERROR Mht2Html - Please remember to remove any sensitive message in the previous lines of log.
2023-10-09 12:23:03,593 [DefaultDispatcher-worker-3] INFO Mht2Html - IMG 082D5EBF-EA9A-4b6a-B365-B8A20856D4C3 doesn't exist!
2023-10-09 12:23:03,593 [DefaultDispatcher-worker-3] INFO Mht2Html - IMG E6993288-116C-49e0-9A9F-A4604A7B87B5 doesn't exist!
2023-10-09 12:23:03,593 [DefaultDispatcher-worker-3] INFO Mht2Html - IMG BEEDE172-9F33-48a8-8FB0-E20D0E5E7FEF doesn't exist!
2023-10-09 12:23:03,593 [DefaultDispatcher-worker-3] INFO Mht2Html - IMG B60D0375-C77A-4ee4-9CED-BD815F2DF243 doesn't exist!
2023-10-09 12:23:03,593 [DefaultDispatcher-worker-3] INFO Mht2Html - IMG F4DC061D-1C81-4a12-885C-2658429DA2B2 doesn't exist!
2023-10-09 12:23:03,598 [DefaultDispatcher-worker-3] INFO Mht2Html - Over line limit: 62393 > 7500. Writing to new file.
2023-10-09 12:23:03,598 [DefaultDispatcher-worker-3] INFO Mht2Html - Going to write to D:\Alvin\Desktop\html
2023-10-09 12:23:03,599 [DefaultDispatcher-worker-3] WARN Mht2Html - Msg contact 《《一串群或讨论组的成员名》》 
2023-10-09 12:23:03,599 [DefaultDispatcher-worker-3] ERROR Mht2Html - Failed to handle line 86539. Line content: <tr><td style=border-bottom-width:1px;border-bottom-color:#8EC3EB;border-bottom-style:solid;color:#3568BB;font-weight:bold;height:24px;line-height:24px;padding-left:10px;margin-bottom:5px;>日期: 2009-11-16</td></tr><tr><td><div style=color:#006EFE;padding-left:10px;><div style=float:left;margin-right:6px;>***)</div>12:05:43</div><div style=padding-left:20px;><IMG src="{F4DC061D-1C81-4a12-885C-2658429DA2B2}.dat"></div></td></tr>.
java.io.IOException: 文件名、目录名或卷标语法不正确。
	at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(Unknown Source)
	at Mht2Html.writeFragmentFile(Mht2Html.kt:418)
	at Mht2Html.processHtml(Mht2Html.kt:320)
	at Mht2Html.access$processHtml(Mht2Html.kt:22)
	at Mht2Html$doJob$1.invokeSuspend(Mht2Html.kt:85)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
java.io.IOException: 文件名、目录名或卷标语法不正确。
	at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(Unknown Source)
	at Mht2Html.writeFragmentFile(Mht2Html.kt:418)
	at Mht2Html.processHtml(Mht2Html.kt:320)
	at Mht2Html.access$processHtml(Mht2Html.kt:22)
	at Mht2Html$doJob$1.invokeSuspend(Mht2Html.kt:85)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2023-10-09 12:23:03,599 [DefaultDispatcher-worker-3] ERROR Mht2Html - Please raise a GitHub issue and attach the log file where you think the exception you hit is important.
2023-10-09 12:23:03,599 [DefaultDispatcher-worker-3] ERROR Mht2Html - Please remember to remove any sensitive message in the previous lines of log.

**Comment by gyakkun** [comment]
看着像是图片输出目录的名称有问题。你在Image Output Folder里面填的是什么值？

**Comment by Alvin0U0** [comment]
图片输出目录名称就是默认的img，图片是可以正常导出的
________________________________
发件人: Gyakkun ***@***.***>
发送时间: 2023年10月10日 3:44
收件人: gyakkun/qq-mht2html ***@***.***>
抄送: Alvin0U0 ***@***.***>; Author ***@***.***>
主题: Re: [gyakkun/qq-mht2html] 导出的html不全，不知道什么原因 (Issue #3)


看着像是图片输出目录的名称有问题。你在Image Output Folder里面填的是什么值？

―

**Comment by gyakkun** [comment]
> 图片输出目录名称就是默认的img，图片是可以正常导出的
> […](#)

抱歉昨晚没看仔细。重新检查了下, 我怀疑是群名的问题。日志里应该有 `WARN Msg contact $msgContact has been sanitized to: $sanitizedFilenamePrefix ` 的一行, 留意到你将它遮住了 (《《一串群或讨论组的成员名》》)。你不妨试试直接在html输出目录新建一个以sanitizedFilenamePrefix为名的文本文件看看成不成功? 有可能是特殊字符/过长等问题。

**Comment by Alvin0U0** [comment]
有的讨论组的名称确实非常长（默认的讨论组名称就是把所有的成员名连一起作为标题），不过并非所有的都很长，但是，所有的群或者讨论组（包括名称正常的）的消息都没有导出来。

我在导出目录html文件夹下新建了sanitizedFilenamePrefix.txt，但是问题依旧。

我查找了原始log文件，没有完全符合"WARN Msg contact $msgContact has been sanitized to: $sanitizedFilenamePrefix" 这样的一行。 最接近的就是如下的内容了：

2023-10-10 11:26:16,964 [DefaultDispatcher-worker-1] INFO Mht2Html - Going to write to D:\Alvin\Desktop\html
2023-10-10 11:26:16,964 [DefaultDispatcher-worker-1] WARN Mht2Html - Msg contact 很长一串名字（有中文，数字，“-”，“、”，“.”）、&nbsp;&nbsp;&nbsp;&nbsp;  QQ名  has been sanitized to:  很长一串名字（有中文，数字，“-”，“、”，“.”）
2023-10-10 11:26:16,964 [DefaultDispatcher-worker-1] ERROR Mht2Html - Failed to handle line 203146. Line content: <tr><td style=border-bottom-width:1px;border-bottom-color:#8EC3EB;border-bottom-style:solid;color:#3568BB;font-weight:bold;height:24px;line-height:24px;padding-left:10px;margin-bottom:5px;>日期: 2015-10-01</td></tr><tr><td><div style=color:#006EFE;padding-left:10px;><div style=float:left;margin-right:6px;> qq名 </div>11:28:14</div><div style=padding-left:20px;><font style="font-size:10pt;font-family:'宋体','MS Sans Serif',sans-serif;" color='000000'>一段消息</font></div></td></tr>.
java.io.IOException: 文件名、目录名或卷标语法不正确。
      at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
      at java.base/java.io.File.createNewFile(Unknown Source)
      at Mht2Html.writeFragmentFile(Mht2Html.kt:418)
      at Mht2Html.processHtml(Mht2Html.kt:320)
      at Mht2Html.access$processHtml(Mht2Html.kt:22)
      at Mht2Html$doJob$1.invokeSuspend(Mht2Html.kt:85)
      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
      at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
java.io.IOException: 文件名、目录名或卷标语法不正确。



________________________________
发件人: Gyakkun ***@***.***>
发送时间: 2023年10月10日 10:45
收件人: gyakkun/qq-mht2html ***@***.***>
抄送: Alvin0U0 ***@***.***>; Author ***@***.***>
主题: Re: [gyakkun/qq-mht2html] 导出的html不全，不知道什么原因 (Issue #3)


图片输出目录名称就是默认的img，图片是可以正常导出的
…

抱歉昨晚没看仔细。重新检查了下, 我怀疑是群名的问题。日志里应该有 WARN Msg contact $msgContact has been sanitized to: $sanitizedFilenamePrefix 的一行, 留意到你将它遮住了 (《《一串群或讨论组的成员名》》)。你不妨试试直接在html输出目录新建一个以sanitizedFilenamePrefix为名的文本文件看看成不成功? 有可能是特殊字符/过长等问题。

**Comment by gyakkun** [comment]
> 有的讨论组的名称确实非常长（默认的讨论组名称就是把所有的成员名连一起作为标题），不过并非所有的都很长，但是，所有的群或者讨论组（包括名称正常的）的消息都没有导出来。

用超长的群名在本地复现这个报错了, 打算加个长度限制, 应该不会很复杂。可能需要你帮忙测试。

**Comment by Alvin0U0** [comment]
好的，没问题
________________________________
发件人: Gyakkun ***@***.***>
发送时间: 2023年10月11日 3:18
收件人: gyakkun/qq-mht2html ***@***.***>
抄送: Alvin0U0 ***@***.***>; Author ***@***.***>
主题: Re: [gyakkun/qq-mht2html] 导出的html不全，不知道什么原因 (Issue #3)


有的讨论组的名称确实非常长（默认的讨论组名称就是把所有的成员名连一起作为标题），不过并非所有的都很长，但是，所有的群或者讨论组（包括名称正常的）的消息都没有导出来。

用超长的群名在本地复现这个报错了, 打算加个长度限制, 应该不会很复杂。可能需要你帮忙测试。

―

**Comment by gyakkun** [comment]
@Alvin0U0 可以试下 v1.2.5 有没有解决你的问题

https://github.com/gyakkun/qq-mht2html/releases/download/v1.2.5/QQ.Mht2html-1.2.5-RH.msi

**Comment by Alvin0U0** [comment]
可以啦，感谢大佬
________________________________
发件人: Gyakkun ***@***.***>
发送时间: 2023年10月12日 1:32
收件人: gyakkun/qq-mht2html ***@***.***>
抄送: Alvin0U0 ***@***.***>; Mention ***@***.***>
主题: Re: [gyakkun/qq-mht2html] 导出的html不全，不知道什么原因 (Issue #3)


@Alvin0U0<https://github.com/Alvin0U0> 可以试下 v1.2.5 有没有解决你的问题

https://github.com/gyakkun/qq-mht2html/releases/download/v1.2.5/QQ.Mht2html-1.2.5-RH.msi

―
